hlndr_tumblr/blog/urls.py
from django.conf.urls import patterns, include, url

urlpatterns = patterns('',
	url(r'^comment/(?P<post_type>\w+)/(?P<post_id>\d+)/$', 'blog.views.new_comment', name='newcomment'),
	url(r'^text/$', 'blog.views.new_text_post', name='newtext'),
	url(r'^photo/$', 'blog.views.new_photo_post', name='newphoto'),
	url(r'^quote/$', 'blog.views.new_quote_post', name='newquote'),
	url(r'^link/$', 'blog.views.new_link_post', name='newlink'),
	url(r'^chat/$', 'blog.views.new_chat_post', name='newchat'),
	url(r'^audio/$', 'blog.views.new_audio_post', name='newaudio'), 
	url(r'^video/$', 'blog.views.new_video_post', name='newvideo'),
)	

hlndr_tumblr/hlndr_tumblr/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'hlndr_tumblr.views.home', name='home'),
    # url(r'^hlndr_tumblr/', include('hlndr_tumblr.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),

	# home page 
	url(r'^$', 'hlndr_tumblr.views.home', name='home'),
	url(r'^register/$', 'users.views.register', name='register'),
	url(r'^login/$', 'users.views.log_in', name='log_in'),
	url(r'^logout/$', 'users.views.log_out', name='log_out'),
	url(r'^dashboard/$', 'dashboard.views.dashboard', name='dashboard'),

	url(r'^post/(?P<post_type>\w+)/(?P<post_id>\d+)/$', 'blog.views.post_page', name='post_page'),
	url(r'^new/', include('blog.urls')),

	url(r'^messages/', include('messages.urls')),

	url(r'^delete/(?P<post_type>\w+)/(?P<post_id>\d+)/$', 'dashboard.views.deletepost', name='deletepost'),

	url(r'^favicon\.ico$', 'django.views.generic.simple.redirect_to', {'url': '/static/img/favicon.ico'}),

   	url(r'^following/$', 'following.views.following', name='following'),
  	url(r'^follow/(?P<username>\w+)/$', 'following.views.follow', name='follow'),
 	url(r'^following/delete/(?P<category>[\w@.+\-\ ]+)/$','following.views.delete_category', name='delete_category'),
	url(r'^following/category/(?P<category>[\w@.+\-\ ]+)/$', 'following.views.view_category', name = 'view_category'),
	url(r'^following/categorize/(?P<category>[\w@.+\-\ ]+)/(?P<otheruser>\w+)/$', 'following.views.categorize', name='categorize'),

	url(r'^friends/$', 'friends.views.friend_page', name='friend_page'),
	url(r'^friends/send/(?P<friendname>\w+)/$', 'friends.views.send_friend_request', name='send_friend_request'),
	url(r'^friends/accept/(?P<friendname>\w+)/$', 'friends.views.friend_add', name='accept_friend_request'),

	url(r'^favorites/$', 'favorites.views.favorites', name='favorites'),

	url(r'^editprofile/$', 'users.views.edit_profile', name="edit_profile"),

	url(r'^postaction/(?P<username>\w+)/$', 'blog.views.blog_post_action', name='blog_post_action'),

	url(r'^(?P<username>\w+)/$', 'blog.views.blogpage', name='blogpage'),
	url(r'^(?P<username>\w+)/posts/$', 'dashboard.views.viewposts', name='viewposts'),
	url(r'^(?P<username>\w+)/profile/$', 'users.views.profile', name='profile'),
)

hlndr_tumblr/blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.template.defaultfilters import slugify
from django.core.exceptions import ObjectDoesNotExist

from taggit.managers import TaggableManager
from constants import *

# Create your models here.

# Encapsulates blog specific information
class Blog(models.Model):
	author = models.ForeignKey(User)
	title = models.CharField(max_length=100, default="Untitled")

class TextPost(models.Model):
	title = models.CharField(max_length=100)
	text = models.TextField()
	post_date = models.DateTimeField(auto_now_add=True)
	author = models.ForeignKey(User)
	privacy = models.IntegerField(choices=privacy_choices, default=PRIVACY_ALL)
	tags = TaggableManager()
	reblogs = models.ManyToManyField('TextPost', related_name="list_parent")

	def __unicode__(self):
		return "author:%s, title:%s, post_date:%s" % (self.author.username, 
													  self.title, 
													  self.post_date)

	def classname(self):
		return self.__class__.__name__

	def custom_html(self):
		html = "<h3>" + self.title + "</h3>"
		html += "<h6>" + self.text + "</h6>"
		return html

class PhotoPost(models.Model):
	filename = models.CharField(max_length=100)
	url = models.URLField()
	caption = models.TextField()
	post_date = models.DateTimeField(auto_now_add=True)
	author = models.ForeignKey(User)
	privacy = models.IntegerField(choices=privacy_choices, default=PRIVACY_ALL)
	tags = TaggableManager()
	reblogs = models.ManyToManyField('PhotoPost', related_name="list_parent")

	def __unicode__(self):
		return "author:%s, filename:%s, post_date:%s" % (self.author.username,
													     self.filename,
														 self.post_date)

	def classname(self):
		return self.__class__.__name__

	def custom_html(self):
		html = """ <img src=" """ + self.url + """ "></img> """
		html += "<h6>" + self.caption + "</h6>"
		return html
	
class VideoPost(models.Model):
	filename = models.CharField(max_length=100)
	url = models.URLField()
	description = models.TextField()
	post_date = models.DateTimeField(auto_now_add=True)
	author = models.ForeignKey(User)
	privacy = models.IntegerField(choices=privacy_choices, default=PRIVACY_ALL)
	tags = TaggableManager()
	reblogs = models.ManyToManyField('VideoPost', related_name="list_parent")

	def __unicode__(self):
		return "author:%s, filename:%s, post_date:%s" % (self.author.username,
													     self.filename,
														 self.post_date)

	def classname(self):
		return self.__class__.__name__

	def custom_html(self):
		html = """ <video width="100%" controls> """
		html += """ <source src="%s" type="vidoe/mp4"> """ % self.url
		html += """ <p> Could not play </p> """
		html += """ </video> """
		html += """ <h6> %s </h6> """ % self.description
		return html

class AudioPost(models.Model):
	filename = models.CharField(max_length=100)
	url = models.URLField()
	description = models.TextField()
	post_date = models.DateTimeField(auto_now_add=True)
	author = models.ForeignKey(User)
	privacy = models.IntegerField(choices=privacy_choices, default=PRIVACY_ALL)
	tags = TaggableManager()
	reblogs = models.ManyToManyField('AudioPost', related_name="list_parent")

	def __unicode__(self):
		return "author:%s, filename:%s, post_date:%s" % (self.author.username,
													     self.filename,
														 self.post_date)

	def classname(self):
		return self.__class__.__name__

	def custom_html(self):
		html = """ <audio controls> """
		html += """ <source src="%s" type="audio/mpeg"> """ % self.url
		html += """ <p> Could not play </p> """
		html += """ </audio> """
		html += """ <h6> %s </h6> """ % self.description
		return html

class QuotePost(models.Model):
	quote = models.TextField()
	source = models.TextField()
	post_date = models.DateTimeField(auto_now_add=True)
	author = models.ForeignKey(User)
	privacy = models.IntegerField(choices=privacy_choices, default=PRIVACY_ALL)
	tags = TaggableManager()
	reblogs = models.ManyToManyField('QuotePost', related_name="list_parent")

	def __unicode__(self):
		return "author:%s, post_date:%s" % (self.author.username, self.post_date)
	
	def classname(self):
		return self.__class__.__name__

	def custom_html(self):
		html = """ <h1> "%s" </h1> """ % self.quote
		html += """ <h5> -%s </h5> """ % self.source
		return html

class LinkPost(models.Model):
	title = models.CharField(max_length=100)
	link = models.URLField()
	description = models.TextField()
	post_date = models.DateTimeField(auto_now_add=True)
	author = models.ForeignKey(User)
	privacy = models.IntegerField(choices=privacy_choices, default=PRIVACY_ALL)
	tags = TaggableManager()
	reblogs = models.ManyToManyField('LinkPost', related_name="list_parent")

	def __unicode__(self):
		return "author:%s, title:%s, post_date:%s" % (self.author.username,
													  self.title,
													  self.post_date)
	def classname(self):
		return self.__class__.__name__

	def custom_html(self):
		html = """ <div class="well container-fluid" style="background-color:#F5F6CE;"> """
		html += """ <a href="%s" class="btn btn-link"><strong> %s </strong></a> """ % (self.link, self.link)
		html += """ </div> """
		html += """ <h2> %s </h2> """ % self.title
		html += """ <h6> %s </h6> """ % self.description
		return html

class ChatPost(models.Model):
	title = models.CharField(max_length=100)
	chat = models.TextField()
	post_date = models.DateTimeField(auto_now_add=True)
	author = models.ForeignKey(User)
	privacy = models.IntegerField(choices=privacy_choices, default=PRIVACY_ALL)
	tags = TaggableManager()
	reblogs = models.ManyToManyField('ChatPost', related_name="list_parent")

	def __unicode__(self):
		return "author:%s, title:%s, post_date:%s" % (self.author.username,
												      self.title,
													  self.post_date)
	def classname(self):
		return self.__class__.__name__

	def custom_html(self):
		html = """ <h3> %s </h3> """ % self.title
		html += """ <h5> %s </h5> """ % self.chat
		return html

# todo: implement comments and likes and reposts
class Like(models.Model):
	textpost = models.ForeignKey(TextPost, null=True)
	photopost = models.ForeignKey(PhotoPost, null=True)
	quotepost = models.ForeignKey(QuotePost, null=True)
	linkpost = models.ForeignKey(LinkPost, null=True)
	chatpost = models.ForeignKey(ChatPost, null=True)
	audiopost = models.ForeignKey(AudioPost, null=True)
	videopost = models.ForeignKey(VideoPost, null=True)
	user = models.ForeignKey(User)

	def __unicode__(self):
		return self.user.username + ',' + self.get_post().classname()

	def get_post(self):
		if self.textpost != None:
			return self.textpost
		if self.photopost != None:
			return self.photopost
		if self.quotepost != None:
			return self.quotepost
		if self.linkpost != None:
			return self.linkpost
		if self.chatpost != None:
			return self.chatpost
		if self.audiopost != None:
			return self.audiopost
		if self.videopost != None:
			return self.videopost

		return None

class Comment(models.Model):
	textpost = models.ForeignKey(TextPost, null=True)
	photopost = models.ForeignKey(PhotoPost, null=True)
	quotepost = models.ForeignKey(QuotePost, null=True)
	linkpost = models.ForeignKey(LinkPost, null=True)
	chatpost = models.ForeignKey(ChatPost, null=True)
	audiopost = models.ForeignKey(AudioPost, null=True)
	videopost = models.ForeignKey(VideoPost, null=True)

	user = models.ForeignKey(User)
	comment = models.TextField()
	post_date = models.DateTimeField(auto_now_add=True)

	def __unicode__(self):
		return self.user.username + ',' + self.get_post().classname()

	def get_post(self):
		if self.textpost != None:
			return self.textpost
		if self.photopost != None:
			return self.photopost
		if self.quotepost != None:
			return self.quotepost
		if self.linkpost != None:
			return self.linkpost
		if self.chatpost != None:
			return self.chatpost
		if self.audiopost != None:
			return self.audiopost
		if self.videopost != None:
			return self.videopost

		return None

hlndr_tumblr/blog/forms.py
from django import forms
from blog.constants import *

class CommentForm(forms.Form):
	comment = forms.CharField(required=True)

class ReblogForm(forms.Form):
	title = forms.CharField(max_length=100, required=False)
	description = forms.CharField(required=False)
	
	quote = forms.CharField(required=False)
	source = forms.CharField(required=False)

	link = forms.URLField(required=False)

	tags = forms.CharField(required=False)
	privacy = forms.ChoiceField(widget=forms.Select(attrs={'class':'span3'}),
								choices=privacy_choices,
								required=True)

class TextForm(forms.Form):
	title = forms.CharField(max_length=100, required=False)
	text = forms.CharField(required=True)
	tags = forms.CharField(required=False)
	privacy = forms.ChoiceField(widget=forms.Select(attrs={'class':'span3'}),
								choices=privacy_choices,
								required=True)

class PhotoForm(forms.Form):
	photo = forms.FileField(required=True)
	caption = forms.CharField(required=False)
	tags = forms.CharField(required=False)
	privacy = forms.ChoiceField(widget=forms.Select(attrs={'class':'span3'}),
								choices=privacy_choices,
								required=True)

class VideoForm(forms.Form):
	video = forms.FileField(required=True)
	description = forms.CharField(required=False)
	tags = forms.CharField(required=False)
	privacy = forms.ChoiceField(widget=forms.Select(attrs={'class':'span3'}),
								choices=privacy_choices,
								required=True)

class AudioForm(forms.Form):
	audio = forms.FileField(required=True)
	description = forms.CharField(required=False)
	tags = forms.CharField(required=False)
	privacy = forms.ChoiceField(widget=forms.Select(attrs={'class':'span3'}),
								choices=privacy_choices,
								required=True)

class QuoteForm(forms.Form):
	quote = forms.CharField(required=True)
	source = forms.CharField(required=False)
	tags = forms.CharField(required=False)
	privacy = forms.ChoiceField(widget=forms.Select(attrs={'class':'span3'}),
								choices=privacy_choices,
								required=True)

class LinkForm(forms.Form):
	title = forms.CharField(max_length=100, required=False)
	link = forms.URLField(required=True)
	description = forms.CharField(required=False)
	tags = forms.CharField(required=False)
	privacy = forms.ChoiceField(widget=forms.Select(attrs={'class':'span3'}),
								choices=privacy_choices,
								required=True)

class ChatForm(forms.Form):
	title = forms.CharField(max_length=100, required=False)
	chat = forms.CharField(required=True)
	tags = forms.CharField(required=False)
	privacy = forms.ChoiceField(widget=forms.Select(attrs={'class':'span3'}),
								choices=privacy_choices,
								required=True)

hlndr_tumblr/templates/blog/audioform.html
{% extends 'dashboard/dashboard.html' %}

{% block title %} New Post &middot; Highlandr {% endblock %}

{% block dashboard_content %}
	<form action="/new/audio/" method="POST" enctype="multipart/form-data">
		{% csrf_token %}
		<h2><i class="icon-headphones"></i> Make an audio post </h2>
		<strong>Viewable for</strong> {{ form.privacy }}

		<h5> {{ invalid }}</h5>
		<div>	
			<p><strong>10MB MAX &middot; MP3 ONLY</strong></p>

			{{ form.audio }}

			{% if form.description.value == None %}
			<textarea rows="10" class="field span12" name="description" id="id_description" placeholder="Description (optional)"></textarea>
			{% else %}
			<textarea rows="10" class="field span12" name="description" id="id_description" value="{{ form.description.value }}" placeholder="Description (optional)"></textarea>
			{% endif %}
			<input type="text" class="input-block-level" name="tags" placeholder="Tags seperated by commas (optional)"></input>
		</div>
		<button type="submit" class="btn btn-block btn-primary"> Post </button>
	</form>

{% endblock %}

hlndr_tumblr/templates/blog/blogpage.html
{% extends 'base.html' %}

{% block title %} {{ blog.title }} {% endblock %}

{% block content %}

<div class="container fill" id="mainbody">
	<div class="row-fluid" id="blogcontainer">
		<div class="container span8 offset1">
			<div></div>
			<div class="well container-fluid span" id="blogname"> 
				<h2> {{ blog.title }}</h2>
			</div>

				{% if reblog_error %}
				<script type="text/javascript">
					$(window).load(function() {
							$('#modal_reblog_error').modal('show');
							});
				</script>

				<div class="modal hide fade" id="modal_reblog_error">
					<div class="modal-body">
						<h4 style="color: #B94A48;"> Could not reblog:<h4>
						<h6 style="color: #B94A48;">{{ reblog_error_message }}<h6>
					</div>
					<div class="modal-footer">
						<a class="btn btn-primary" data-dismiss="modal">Close</a>
					</div>
				</div>
				{% endif %}
				
				{% for post in posts %}
				<div class="modal hide fade" id="modal_{{post.classname}}_{{post.id}}">
					<div class="modal-body" style="max-height: 300px;">
						{% autoescape off %}
						{% filter linebreaksbr %}{{ post.custom_html }}{% endfilter %}
						{% endautoescape %}

						<h5>
						{% for tag in post.tags.all %}
						<small style="color:#EC3B86;">#{{ tag.name }} </small>
						{% endfor %}
						</h5>

					</div>
					<div class="modal-footer">
					<form id="reblog_action_form" action="." method="POST">
						{% csrf_token %}
						<strong>Viewable by:</strong> {{ reblog_form.privacy }}
						{% if post.classname == 'TextPost' or post.classname == 'LinkPost' or post.classname == 'ChatPost' %}
						<input type="text" class="input-block-level" name="title" value="{{post.title}}" placeholder="Title (optional)"></input>
						{% endif %}
						{% if post.classname == 'LinkPost' %}
						<input type="url" class="input-block-level" name="link" value="{{post.link}}" placeholder="URL"></input>
						{% endif %}
						{% if post.classname != 'QuotePost' %}
						<textarea class="span" rows="8" name="description">{{post.description}}{{post.caption}}{{post.text}}</textarea>
						{% endif %}
						{% if post.classname == 'QuotePost' %}
						<textarea class="span" rows="6" name="quote" placeholder="Quote">{{post.quote}}</textarea>
						<textarea class="span" rows="6" name="source" placeholder="Source (optional)">{{post.source}}</textarea>
						{% endif %}
						<input type="text" class="input-block-level" name="tags" placeholder="Tags, separated, by, commas, (optional)"></input>
						<button href="." class="btn btn-primary pull-left" type="submit" name="reblog_action" value="reblog_{{post.classname}}_{{post.id}}">
						<i class="icon-retweet"></i> Reblog 
						</button>
					</form>
					</div>
				</div>				

				<div class="well container-fluid span" id="blogpost">
	
					<form id="post_action_form" align="right" action="/postaction/{{author.username}}/" method="POST">
						{% csrf_token %}
						<a href="/post/{{post.classname}}/{{post.id}}/" value="comment" class="post_action_button">
							<i class="icon-comment"></i> {{ post.comment_set.count }}
						</a>

						<button href="." type="submit" name="post_action" value="like_{{post.classname}}_{{post.id}}" class="post_action_button">
							<i class="icon-heart"></i> {{ post.like_set.count }}
						</button>

						<button href="#modal_{{post.classname}}_{{post.id}}" data-toggle="modal" type="submit" name="post_action" value="reblog_{{post.classname}}_{{post.id}}" class="post_action_button">
							<i class="icon-retweet"></i> {{ post.reblogs.count }}
						</button>

						<button href="." type="submit" name="post_action" value="favorite_{{post.classname}}_{{post.id}}" class="post_action_button">
							{% if post in user.favelist.get_favorites %}
							<i class="icon-star" style="color:#86860C;"></i>
							{% else %}
							<i class="icon-star"></i>
							{% endif %}
						</button>
					</form>
			
					<h6> {{ post.post_date }} </h6>
					{% autoescape off %}
					{% filter linebreaksbr %}{{ post.custom_html }}{% endfilter %}
					{% endautoescape %}
					
					<h5>
					{% for tag in post.tags.all %}
					<small style="color:#EC3B86;">#{{ tag.name }} </small>
					{% endfor %}
					</h5>

				</div>
				{% endfor %}
		</div>

		<div class="container span2">
			{% if is_friend %}
			<button class="btn btn-block-level disabled span12"><i class="icon-ok"></i> Friend </button>
			{% else %}
				{% if author == user %}
				<button class="btn btn-block-level disabled span12">Send Friend Request </button>
				{% else %}			
				<a href="/friends/send/{{ author.username }}/" class="btn btn-block-level span12">Send Friend Request </a>
				{% endif %}
			{% endif %}
			<ul class="thumbnails">
				<li class="span" style="padding:20px 20px 0px;">
					<a href="/{{ author.username }}/profile/" class="thumbnail">
						{% if author.userprofile.avatar == "" %}
						<img src="../../static/img/default_avatar.png" class="img-rounded" height="200" width="200"></img>
						{% else %}
						<img src="{{ author.userprofile.avatar }}" class="img-rounded" height="200" width="200"></img>
						{% endif %}
					</a>
				</li>
				<li class="span" style="padding:0px 20px;">	
					<a href="/{{ author.username }}/profile/" class="btn btn-small btn-info"> Profile </a>
         	<a href="/follow/{{ author.username }}/" class="btn btn-small btn-info"> Follow </a>
				</li>
			</ul>
		</div>

	</div>
</div>

{% endblock %}

hlndr_tumblr/templates/blog/chatform.html
{% extends 'dashboard/dashboard.html' %}

{% block title %} New Post &middot; Highlandr {% endblock %}

{% block dashboard_content %}
	<form action="/new/chat/" method="POST" class="">
		{% csrf_token %}
		<h2><i class="icon-comments"></i> Make a chat post </h2>
		<strong>Viewable for</strong> {{ form.privacy }}

		<h5> {{ invalid }} </h5>
		<div>
			{% if form.title.value == None %}
			<input type="text" class="input-block-level" name="title" id="id_title" placeholder="Title (optional)">	
			{% else %}
			<input type="text" class="input-block-level" name="title" id="id_title" value="{{ form.title.value }}" placeholder="Title (optional)">	
			{% endif %}

			{% if form.chat.value == None %}
			<textarea rows="10" class="field span12" name="chat" id="id_chat" placeholder="Stranger: Whatdya got?
																			Merchant: Not enough cash, stranger!"></textarea>
			{% else %}
			<textarea rows="10" class="field span12" name="chat" id="id_chat" title="Stranger: Whatdya got?
																			Merchant: Not enough cash, stranger!"></textarea>
			{% endif %}
			<input type="text" class="input-block-level" name="tags" placeholder="Tags seperated by commas (optional)"></input>
		</div>
		<button type="submit" class="btn btn-block btn-primary"> Post </button>
	</form>
{% endblock %}

hlndr_tumblr/templates/blog/linkform.html
{% extends 'dashboard/dashboard.html' %}

{% block title %} New Post &middot; Highlandr {% endblock %}

{% block dashboard_content %}
	<form action="/new/link/" method="POST" class="">
		{% csrf_token %}
		<h2><i class="icon-link"></i> Make a link post </h2>
		<strong>Viewable for</strong> {{ form.privacy }}

		<h5> {{ invalid }} </h5>
		<div>
			{% if form.title.value == None %}
			<input type="text" class="input-block-level" name="title" id="id_title" placeholder="Title (optional)"></input>
			{% else %}
			<input type="text" class="input-block-level" name="title" id="id_title" value="{{ form.title.value }}" placeholder="Title (optional)"></input>
			{% endif %}

			{% if form.link.value == None %}
			<input type="url" class="input-block-level" name="link" id="id_link" placeholder="URL"></input>
			{% else %}
			<input type="url" class="input-block-level" name="link" id="id_link" value="{{ form.link.value }}" placeholder="URL"></input>
			{% endif %}

			{% if form.description.value == None %}
			<textarea rows="10" class="field span12" name="description" id="id_description" placeholder="Description (optional)"></textarea>
			{% else %}
			<textarea rows="10" class="field span12" name="description" id="id_description" value="{{ form.text.value }}" placeholder="Description(optional)"></textarea>
			{% endif %}
			<input type="text" class="input-block-level" name="tags" placeholder="Tags seperated by commas (optional)"></input>
		<div>
		<button type="submit" class="btn btn-block btn-primary"> Post </button>
	</form>
{% endblock %}

hlndr_tumblr/templates/blog/photoform.html
{% extends 'dashboard/dashboard.html' %}

{% block title %} New Post &middot; Highlandr{% endblock %}

{% block dashboard_content %}
	<form action="/new/photo/" method="POST" enctype="multipart/form-data" class="">
		{% csrf_token %}
		<h2><i class="icon-camera"></i> Make a photo post </h2>
		<strong>Viewable for</strong> {{ form.privacy }}

		<h5> {{ invalid }}</h5>
		<div>
			{{ form.photo }}
			{% if form.caption.value == None %}
			<textarea rows="10" class="field span12" name="caption" id="id_caption" placeholder="Caption (optional)"></textarea>
			{% else %}
			<textarea rows="10" class="field span12" name="caption" id="id_caption" value="{{ form.caption.value }}" placeholder="Caption (optional)"></textarea>
			{% endif %}
			<input type="text" class="input-block-level" name="tags" placeholder="Tags seperated by commas (optional)"></input>
		</div>
		<button type="submit" class="btn btn-block btn-primary"> Post </button>
	</form>
{% endblock %}

hlndr_tumblr/templates/blog/quoteform.html
{% extends 'dashboard/dashboard.html' %}

{% block title %} New Post &middot; Highlandr {% endblock %}

{% block dashboard_content %}
	<form action="/new/quote/" method="POST" class="">
		{% csrf_token %}
		<h2><i class="icon-quote-left"></i> Make a quote post </h2>
		<strong>Viewable for</strong> {{ form.privacy }}

		<h5> {{ invalid }} </h5>
		<div>
			<textarea rows="6" class="field span12" name="quote" id="id_quote" value="{{ form.quote.value }}" placeholder="Quote"></textarea>
			{% if form.source.value == None %}
			<textarea rows="6" class="field span12" name="source" id="id_source" placeholder="Source (optional)"></textarea>
			{% else %}
			<textarea rows="6" class="field span12" name="source" id="id_source" value="{{ form.source.value }}" placeholder="Source (optional)"></textarea>
			{% endif %}
       <input type="text" class="input-block-level" name="tags" placeholder="Tags seperated by commas (optional)"></input>
		</div>
		<button type="submit" class="btn btn-block btn-primary"> Post </button>
	</form>
{% endblock %}

hlndr_tumblr/templates/blog/textform.html
{% extends 'dashboard/dashboard.html' %}

{% block title %} New Post &middot; Highlandr {% endblock %}

{% block dashboard_content %}
	<form action="/new/text/" method="POST">
		{% csrf_token %}
		<h2><i class="icon-font"></i> Make a text post </h2>
		<strong>Viewable for</strong> {{ form.privacy }}

		<h5> {{ invalid }} </h5>
		<div>
			{% if form.title.value == None %}
			<input type="text" class="input-block-level" name="title" id="id_title" placeholder="Title (optional)">	
			{% else %}
			<input type="text" class="input-block-level" name="title" id="id_title" value="{{ form.title.value }}" placeholder="Title (optional)">	
			{% endif %}
			<textarea rows="10" class="field span12" name="text" id="id_text" value="{{ form.text.value }}"></textarea>	
       <input type="text" class="input-block-level" name="tags" placeholder="Tags seperated by commas (optional)"></input>
			</div>
		<button type="submit" class="btn btn-block btn-primary"> Post </button>
	</form>
{% endblock %}