hlndr_tumblr/blog/urls.py
from django.conf.urls import patterns, include, url

urlpatterns = patterns('',
	url(r'^comment/(?P<post_type>\w+)/(?P<post_id>\d+)/$', 'blog.views.new_comment', name='newcomment'),
	url(r'^text/$', 'blog.views.new_text_post', name='newtext'),
	url(r'^photo/$', 'blog.views.new_photo_post', name='newphoto'),
	url(r'^quote/$', 'blog.views.new_quote_post', name='newquote'),
	url(r'^link/$', 'blog.views.new_link_post', name='newlink'),
	url(r'^chat/$', 'blog.views.new_chat_post', name='newchat'),
	url(r'^audio/$', 'blog.views.new_audio_post', name='newaudio'), 
	url(r'^video/$', 'blog.views.new_video_post', name='newvideo'),
)	

hlndr_tumblr/hlndr_tumblr/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'hlndr_tumblr.views.home', name='home'),
    # url(r'^hlndr_tumblr/', include('hlndr_tumblr.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),

	# home page 
	url(r'^$', 'hlndr_tumblr.views.home', name='home'),
	url(r'^register/$', 'users.views.register', name='register'),
	url(r'^login/$', 'users.views.log_in', name='log_in'),
	url(r'^logout/$', 'users.views.log_out', name='log_out'),
	url(r'^dashboard/$', 'dashboard.views.dashboard', name='dashboard'),

	url(r'^post/(?P<post_type>\w+)/(?P<post_id>\d+)/$', 'blog.views.post_page', name='post_page'),
	url(r'^new/', include('blog.urls')),

	url(r'^messages/', include('messages.urls')),

	url(r'^delete/(?P<post_type>\w+)/(?P<post_id>\d+)/$', 'dashboard.views.deletepost', name='deletepost'),

	url(r'^favicon\.ico$', 'django.views.generic.simple.redirect_to', {'url': '/static/img/favicon.ico'}),

   	url(r'^following/$', 'following.views.following', name='following'),
  	url(r'^follow/(?P<username>\w+)/$', 'following.views.follow', name='follow'),
 	url(r'^following/delete/(?P<category>[\w@.+\-\ ]+)/$','following.views.delete_category', name='delete_category'),
	url(r'^following/category/(?P<category>[\w@.+\-\ ]+)/$', 'following.views.view_category', name = 'view_category'),
	url(r'^following/categorize/(?P<category>[\w@.+\-\ ]+)/(?P<otheruser>\w+)/$', 'following.views.categorize', name='categorize'),

	url(r'^friends/$', 'friends.views.friend_page', name='friend_page'),
	url(r'^friends/send/(?P<friendname>\w+)/$', 'friends.views.send_friend_request', name='send_friend_request'),
	url(r'^friends/accept/(?P<friendname>\w+)/$', 'friends.views.friend_add', name='accept_friend_request'),

	url(r'^favorites/$', 'favorites.views.favorites', name='favorites'),

	url(r'^editprofile/$', 'users.views.edit_profile', name="edit_profile"),

	url(r'^postaction/(?P<username>\w+)/$', 'blog.views.blog_post_action', name='blog_post_action'),

	url(r'^(?P<username>\w+)/$', 'blog.views.blogpage', name='blogpage'),
	url(r'^(?P<username>\w+)/posts/$', 'dashboard.views.viewposts', name='viewposts'),
	url(r'^(?P<username>\w+)/profile/$', 'users.views.profile', name='profile'),
)

hlndr_tumblr/blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.template.defaultfilters import slugify
from django.core.exceptions import ObjectDoesNotExist

from taggit.managers import TaggableManager
from constants import *

# Create your models here.

# Encapsulates blog specific information
class Blog(models.Model):
	author = models.ForeignKey(User)
	title = models.CharField(max_length=100, default="Untitled")

class TextPost(models.Model):
	title = models.CharField(max_length=100)
	text = models.TextField()
	post_date = models.DateTimeField(auto_now_add=True)
	author = models.ForeignKey(User)
	privacy = models.IntegerField(choices=privacy_choices, default=PRIVACY_ALL)
	tags = TaggableManager()
	reblogs = models.ManyToManyField('TextPost', related_name="list_parent")

	def __unicode__(self):
		return "author:%s, title:%s, post_date:%s" % (self.author.username, 
													  self.title, 
													  self.post_date)

	def classname(self):
		return self.__class__.__name__

	def custom_html(self):
		html = "<h3>" + self.title + "</h3>"
		html += "<h6>" + self.text + "</h6>"
		return html

class PhotoPost(models.Model):
	filename = models.CharField(max_length=100)
	url = models.URLField()
	caption = models.TextField()
	post_date = models.DateTimeField(auto_now_add=True)
	author = models.ForeignKey(User)
	privacy = models.IntegerField(choices=privacy_choices, default=PRIVACY_ALL)
	tags = TaggableManager()
	reblogs = models.ManyToManyField('PhotoPost', related_name="list_parent")

	def __unicode__(self):
		return "author:%s, filename:%s, post_date:%s" % (self.author.username,
													     self.filename,
														 self.post_date)

	def classname(self):
		return self.__class__.__name__

	def custom_html(self):
		html = """ <img src=" """ + self.url + """ "></img> """
		html += "<h6>" + self.caption + "</h6>"
		return html
	
class VideoPost(models.Model):
	filename = models.CharField(max_length=100)
	url = models.URLField()
	description = models.TextField()
	post_date = models.DateTimeField(auto_now_add=True)
	author = models.ForeignKey(User)
	privacy = models.IntegerField(choices=privacy_choices, default=PRIVACY_ALL)
	tags = TaggableManager()
	reblogs = models.ManyToManyField('VideoPost', related_name="list_parent")

	def __unicode__(self):
		return "author:%s, filename:%s, post_date:%s" % (self.author.username,
													     self.filename,
														 self.post_date)

	def classname(self):
		return self.__class__.__name__

	def custom_html(self):
		html = """ <video width="100%" controls> """
		html += """ <source src="%s" type="vidoe/mp4"> """ % self.url
		html += """ <p> Could not play </p> """
		html += """ </video> """
		html += """ <h6> %s </h6> """ % self.description
		return html

class AudioPost(models.Model):
	filename = models.CharField(max_length=100)
	url = models.URLField()
	description = models.TextField()
	post_date = models.DateTimeField(auto_now_add=True)
	author = models.ForeignKey(User)
	privacy = models.IntegerField(choices=privacy_choices, default=PRIVACY_ALL)
	tags = TaggableManager()
	reblogs = models.ManyToManyField('AudioPost', related_name="list_parent")

	def __unicode__(self):
		return "author:%s, filename:%s, post_date:%s" % (self.author.username,
													     self.filename,
														 self.post_date)

	def classname(self):
		return self.__class__.__name__

	def custom_html(self):
		html = """ <audio controls> """
		html += """ <source src="%s" type="audio/mpeg"> """ % self.url
		html += """ <p> Could not play </p> """
		html += """ </audio> """
		html += """ <h6> %s </h6> """ % self.description
		return html

class QuotePost(models.Model):
	quote = models.TextField()
	source = models.TextField()
	post_date = models.DateTimeField(auto_now_add=True)
	author = models.ForeignKey(User)
	privacy = models.IntegerField(choices=privacy_choices, default=PRIVACY_ALL)
	tags = TaggableManager()
	reblogs = models.ManyToManyField('QuotePost', related_name="list_parent")

	def __unicode__(self):
		return "author:%s, post_date:%s" % (self.author.username, self.post_date)
	
	def classname(self):
		return self.__class__.__name__

	def custom_html(self):
		html = """ <h1> "%s" </h1> """ % self.quote
		html += """ <h5> -%s </h5> """ % self.source
		return html

class LinkPost(models.Model):
	title = models.CharField(max_length=100)
	link = models.URLField()
	description = models.TextField()
	post_date = models.DateTimeField(auto_now_add=True)
	author = models.ForeignKey(User)
	privacy = models.IntegerField(choices=privacy_choices, default=PRIVACY_ALL)
	tags = TaggableManager()
	reblogs = models.ManyToManyField('LinkPost', related_name="list_parent")

	def __unicode__(self):
		return "author:%s, title:%s, post_date:%s" % (self.author.username,
													  self.title,
													  self.post_date)
	def classname(self):
		return self.__class__.__name__

	def custom_html(self):
		html = """ <div class="well container-fluid" style="background-color:#F5F6CE;"> """
		html += """ <a href="%s" class="btn btn-link"><strong> %s </strong></a> """ % (self.link, self.link)
		html += """ </div> """
		html += """ <h2> %s </h2> """ % self.title
		html += """ <h6> %s </h6> """ % self.description
		return html

class ChatPost(models.Model):
	title = models.CharField(max_length=100)
	chat = models.TextField()
	post_date = models.DateTimeField(auto_now_add=True)
	author = models.ForeignKey(User)
	privacy = models.IntegerField(choices=privacy_choices, default=PRIVACY_ALL)
	tags = TaggableManager()
	reblogs = models.ManyToManyField('ChatPost', related_name="list_parent")

	def __unicode__(self):
		return "author:%s, title:%s, post_date:%s" % (self.author.username,
												      self.title,
													  self.post_date)
	def classname(self):
		return self.__class__.__name__

	def custom_html(self):
		html = """ <h3> %s </h3> """ % self.title
		html += """ <h5> %s </h5> """ % self.chat
		return html

# todo: implement comments and likes and reposts
class Like(models.Model):
	textpost = models.ForeignKey(TextPost, null=True)
	photopost = models.ForeignKey(PhotoPost, null=True)
	quotepost = models.ForeignKey(QuotePost, null=True)
	linkpost = models.ForeignKey(LinkPost, null=True)
	chatpost = models.ForeignKey(ChatPost, null=True)
	audiopost = models.ForeignKey(AudioPost, null=True)
	videopost = models.ForeignKey(VideoPost, null=True)
	user = models.ForeignKey(User)

	def __unicode__(self):
		return self.user.username + ',' + self.get_post().classname()

	def get_post(self):
		if self.textpost != None:
			return self.textpost
		if self.photopost != None:
			return self.photopost
		if self.quotepost != None:
			return self.quotepost
		if self.linkpost != None:
			return self.linkpost
		if self.chatpost != None:
			return self.chatpost
		if self.audiopost != None:
			return self.audiopost
		if self.videopost != None:
			return self.videopost

		return None

class Comment(models.Model):
	textpost = models.ForeignKey(TextPost, null=True)
	photopost = models.ForeignKey(PhotoPost, null=True)
	quotepost = models.ForeignKey(QuotePost, null=True)
	linkpost = models.ForeignKey(LinkPost, null=True)
	chatpost = models.ForeignKey(ChatPost, null=True)
	audiopost = models.ForeignKey(AudioPost, null=True)
	videopost = models.ForeignKey(VideoPost, null=True)

	user = models.ForeignKey(User)
	comment = models.TextField()
	post_date = models.DateTimeField(auto_now_add=True)

	def __unicode__(self):
		return self.user.username + ',' + self.get_post().classname()

	def get_post(self):
		if self.textpost != None:
			return self.textpost
		if self.photopost != None:
			return self.photopost
		if self.quotepost != None:
			return self.quotepost
		if self.linkpost != None:
			return self.linkpost
		if self.chatpost != None:
			return self.chatpost
		if self.audiopost != None:
			return self.audiopost
		if self.videopost != None:
			return self.videopost

		return None

hlndr_tumblr/dashboard/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Notification(models.Model):
	user = models.ForeignKey(User)
	message = models.CharField(max_length=200)
	link = models.CharField(max_length=200)	

hlndr_tumblr/dashboard/views.py
#Create your views here.
from django.http import HttpResponseRedirect, Http404
from django.template import RequestContext
from django.shortcuts import render_to_response
from django.contrib.auth.decorators import login_required

from utils.shortcuts import *
from dashboard.models import Notification

@login_required(login_url='/login/')
def dashboard(request):
	if request.user.is_authenticated():
		user = request.user

	posts = get_followed_posts(request.user) + get_user_posts(request.user) + get_friend_posts(request.user)
	posts = filter_posts_by_privacy(user, posts)
	posts = list(set(posts))	
	if request.method == 'POST':
		if 'searchbar' in request.POST:
			posts = sort_posts_by_searchbar(posts, request)
		if 'delete_notification' in request.POST:
			notification_id = int(request.POST['delete_notification'])
			notification = Notification.objects.get(id=notification_id)
			link = notification.link
			notification.delete()
			return HttpResponseRedirect(link)
	else:
		posts = sort_posts_by_newest(posts)

	recommendations = rank_blogs(request.user)

	return render_to_response('dashboard/dashboard.html',
							  {'posts':posts, 'recommendations':recommendations}, 
							  context_instance=RequestContext(request))

@login_required(login_url='/login/')
def deletepost(request, post_type, post_id):
	posts = get_user_posts(request.user)
	for post in posts:
		if post.classname().lower() == post_type:
			if post.id == int(post_id):
				delete_post(post)
				return HttpResponseRedirect('/' + request.user.username + '/posts/')
	raise Http404

@login_required(login_url='/login/')
def viewposts(request, username):
	posts = get_user_posts(request.user)
	if request.method == 'POST':
		query = request.POST['searchbar']
		if query == 'newest':
			posts = sort_posts_by_newest(posts)
		elif query == 'oldest':
			posts = sort_posts_by_oldest(posts)
		elif query == 'search':
			# Implement search by tags here
			tags = request.POST['searchbox']
			taglist = get_tag_list(tags)

			posts = []
			for tag in taglist:
				posts += get_user_posts_by_tag(request.user,tag)	
		else:
			posts = sort_posts_by_newest(posts)
	else:
		posts = sort_posts_by_newest(posts)
	
	return render_to_response('dashboard/viewposts.html',
							  {'posts':posts, 'user':request.user},
							  context_instance=RequestContext(request))			

hlndr_tumblr/templates/dashboard/dashboard.html
{% extends 'base.html' %}

{% block title %} Dashboard &middot; Highlandr{% endblock %}

{% block page-container %}dashboard-page-container{% endblock %}

{% block content %}

<div class="container fill" id="mainbody">
	<div class="row-fluid span8 offset2">
		<div class="well span12" style="background-color:#eee;">

		<h2>{% block dash_head %} <i class="icon-dashboard"></i> Dashboard {% endblock %}</h2>

		<div class="container">
			<ul class="nav nav-pills">
			
				<li> <a href="/{{ user.username }}/"> Blog </a> </li>
				<li> <a href="/{{user.username}}/profile/">Profile</a></li>	
				<li> <a href="/dashboard/"> Dashboard </a> </li>
				
				<li class="dropdown">
					<a class="dropwdown-toggle" id="drop4" role="button" data-toggle="dropdown" href="#"><i class="icon-edit"></i> Post<b class="caret"></b></a>
					<ul id="menu1" class="dropdown-menu" role="menu" aria-labelledby="drop4">
						<li role="presentation"><a role="menuitem" href="/new/text/"><i class="icon-font"></i> Text</a></li>
						<li role="presentation"><a role="menuitem" href="/new/photo/"><i class="icon-camera"></i> Photo</a></li>
						<li role="presentation"><a role="menuitem" href="/new/quote/"><i class="icon-quote-left"></i> Quote</a></li>
						<li role="presentation"><a role="menuitem" href="/new/link/"><i class="icon-link"></i> Link</a></li>
						<li role="presentation"><a role="menuitem" href="/new/chat/"><i class="icon-comments"></i> Chat</a></li>
						<li role="presentation"><a role="menuitem" href="/new/audio/"><i class="icon-headphones"></i> Audio</a></li>
						<li role="presentation"><a role="menuitem" href="/new/video/"><i class="icon-facetime-video"></i> Video</a></li>
					</ul>
				</li>
				<li class="dropdown">
					<a class="dropwdown-toggle" id="drop4" role="button" data-toggle="dropdown" href="#"><i class="icon-list-alt"></i> Menu<b class="caret"></b></a>
					<ul id="menu1" class="dropdown-menu" role="menu" aria-labelledby="drop4">
						<li role="presentation"><a role="menuitem" href="/logout/"><i class="icon-signout"></i> Logout</a></li>
						<li role="presentation" class="divider"></li>	
						<li role="presentation"><a role="menuitem" href="/{{user.username}}/posts/"><i class="icon-th-large"></i> Posts</a></li>
						<li role="presentation"><a role="menuitem" href="/favorites/"><i class="icon-star"></i> Favorites</a></li>
						<li role="presentation"><a role="menuitem" href="/friends/"><i class="icon-group"></i> Friends</a></li>
						<li role="presentation"><a role="menuitem" href="/following/"><i class="icon-bookmark"></i> Following</a></li>
						<li role="presentation"><a role="menuitem" href="/messages/"><i class="icon-envelope-alt"></i> Messages</a></li>
					</ul>
				</li>
			</ul>				
		</div>

		<hr style="border-color:#997D83;"> 

			{% block dashboard_content %}
			<form method='POST' action=".">
			{% csrf_token %}
			{% for notification in user.notification_set.all %}
			<div align="center" style="background-color:#FF7373; margin:0px 0px 2px;">
				<button class="delete-notification" type="submit" name="delete_notification" value="{{notification.id}}"> 
				<strong>{{ notification.message }}</strong>
				</button>
			</div>
			{% endfor %}
			</form>
			
			{% if user.notification_set.count != 0 %}	
			<hr style="border-color:#997D83;">
			{% endif %}
		
				<form method='POST' action=".">
				{% csrf_token %}
					<div class="input-prepend input-append" style="margin: 0px; padding:0px 0px;">
						<button class="btn btn-info" type="submit" name="searchbar" value="newest"> Newest </button>
						<button class="btn btn-info" type="submit" name="searchbar" value="oldest"> Oldest </button>
						<input class="span8" name="searchbox" id="appendedInputButtons" type="text" placeholder="tags, seperated by, commas">
						<button class="btn btn-primary" type="submit" name="searchbar" value="search"><i class="icon-search icon-white"></i> Search </button>
					</div>
				</form>

				<div ddclass="container span12" style="margin: 0px;">
				{% for post in posts %}
					<div class="well container-fluid span" id="dashboard-blogpost" style="margin: 5px 0px;">
						
						<a href="/{{ post.author.username }}/">{{ post.author.username }}</a>

						<h6> {{ post.post_date }} </h6>
						{% autoescape off %}
						{% filter linebreaksbr %}{{	post.custom_html }}{% endfilter %}
						{% endautoescape %}

						<h5>
						{% for tag in post.tags.all %}
						<small style="color:#EC3B86;">#{{tag.name}} </small>
						{% endfor %}
						</h5>
			
					</div>
				{% endfor %}
				</div>

			{% endblock %}
		</div>
	</div>
</div>

{% endblock %}

hlndr_tumblr/templates/dashboard/viewposts.html
{% extends 'dashboard/dashboard.html' %}

{% block title %} Posts &middot; Highlandr {% endblock %}

{% block dash_head %} <i class="icon-th-large"></i> Posts {% endblock %}

	{% block dashboard_content %}	
		<form method='POST' action=".">
		{% csrf_token %}
			<div class="input-prepend input-append" style="margin: 0px; padding:0px 0px;">
				<button class="btn btn-info" type="submit" name="searchbar" value="newest"> Newest </button>
				<button class="btn btn-info" type="submit" name="searchbar" value="oldest"> Oldest </button>
				<input class="span8" name="searchbox" id="appendedInputButtons" type="text" placeholder="tags, seperated by, commas">
				<button class="btn btn-primary" type="submit" name="searchbar" value="search"><i class="icon-search icon-white"></i> Search</button>
			</div>
		</form>

				{% for post in posts %}
				<div class="well container-fluid span" id="blogpost" style="margin: 5px 0px;">
					
					<p>
						<strong>Viewable by: 	
						{{post.get_privacy_display}} 
						</strong>
						<a align="left" class="close" href="/delete/{{post.classname|lower}}/{{post.id}}/">&times;</a>
					</p>
			
					<h6> {{ post.post_date }} </h6>
					{% autoescape off %}
					{% filter linebreaksbr %}{{ post.custom_html }}{% endfilter %}
					{% endautoescape %}

					<h5>
					{% for tag in post.tags.all %}
					<small style="color:#EC3B86;">#{{tag.name}} </small>
					{% endfor %}
					</h5>

				</div>
				{% endfor %}
			{% endblock %}