hlndr_tumblr/blog/urls.py
from django.conf.urls import patterns, include, url

urlpatterns = patterns('',
	url(r'^comment/(?P<post_type>\w+)/(?P<post_id>\d+)/$', 'blog.views.new_comment', name='newcomment'),
	url(r'^text/$', 'blog.views.new_text_post', name='newtext'),
	url(r'^photo/$', 'blog.views.new_photo_post', name='newphoto'),
	url(r'^quote/$', 'blog.views.new_quote_post', name='newquote'),
	url(r'^link/$', 'blog.views.new_link_post', name='newlink'),
	url(r'^chat/$', 'blog.views.new_chat_post', name='newchat'),
	url(r'^audio/$', 'blog.views.new_audio_post', name='newaudio'), 
	url(r'^video/$', 'blog.views.new_video_post', name='newvideo'),
)	

hlndr_tumblr/hlndr_tumblr/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'hlndr_tumblr.views.home', name='home'),
    # url(r'^hlndr_tumblr/', include('hlndr_tumblr.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),

	# home page 
	url(r'^$', 'hlndr_tumblr.views.home', name='home'),
	url(r'^register/$', 'users.views.register', name='register'),
	url(r'^login/$', 'users.views.log_in', name='log_in'),
	url(r'^logout/$', 'users.views.log_out', name='log_out'),
	url(r'^dashboard/$', 'dashboard.views.dashboard', name='dashboard'),

	url(r'^post/(?P<post_type>\w+)/(?P<post_id>\d+)/$', 'blog.views.post_page', name='post_page'),
	url(r'^new/', include('blog.urls')),

	url(r'^messages/', include('messages.urls')),

	url(r'^delete/(?P<post_type>\w+)/(?P<post_id>\d+)/$', 'dashboard.views.deletepost', name='deletepost'),

	url(r'^favicon\.ico$', 'django.views.generic.simple.redirect_to', {'url': '/static/img/favicon.ico'}),

   	url(r'^following/$', 'following.views.following', name='following'),
  	url(r'^follow/(?P<username>\w+)/$', 'following.views.follow', name='follow'),
 	url(r'^following/delete/(?P<category>[\w@.+\-\ ]+)/$','following.views.delete_category', name='delete_category'),
	url(r'^following/category/(?P<category>[\w@.+\-\ ]+)/$', 'following.views.view_category', name = 'view_category'),
	url(r'^following/categorize/(?P<category>[\w@.+\-\ ]+)/(?P<otheruser>\w+)/$', 'following.views.categorize', name='categorize'),

	url(r'^friends/$', 'friends.views.friend_page', name='friend_page'),
	url(r'^friends/send/(?P<friendname>\w+)/$', 'friends.views.send_friend_request', name='send_friend_request'),
	url(r'^friends/accept/(?P<friendname>\w+)/$', 'friends.views.friend_add', name='accept_friend_request'),

	url(r'^favorites/$', 'favorites.views.favorites', name='favorites'),

	url(r'^editprofile/$', 'users.views.edit_profile', name="edit_profile"),

	url(r'^postaction/(?P<username>\w+)/$', 'blog.views.blog_post_action', name='blog_post_action'),

	url(r'^(?P<username>\w+)/$', 'blog.views.blogpage', name='blogpage'),
	url(r'^(?P<username>\w+)/posts/$', 'dashboard.views.viewposts', name='viewposts'),
	url(r'^(?P<username>\w+)/profile/$', 'users.views.profile', name='profile'),
)

hlndr_tumblr/users/models.py
from django.db import models
from django.db.models.signals import post_save
from django.contrib.auth.models import User

from blog.models import Like
from favorites.models import FaveList

# Create your models here.
class UserProfile(models.Model):
  	GENDER_CHOICES = (
		('u', 'Undisclosed'),
		('m', 'Male'),
		('f', 'Female'),
	)
    
	user = models.OneToOneField(User)
    
    #following logic
	following = models.ManyToManyField('UserProfile', related_name="list_following")

	#favorites
	#favorites = models.OneToOneField(FaveList, related_name='list_favorites')

	# URL to avatar image hosted
	avatar = models.URLField()
	nickname = models.CharField(max_length=50, blank=True)
	gender = models.CharField(max_length=1, choices=GENDER_CHOICES, blank=True)
	birthday = models.DateField()
	interests = models.CharField(max_length=500, blank=True)

	def __unicode__(self):
        #prepended with 'self.' to resolve scoping issues within the shell
		return self.user.username

	# like a particular post
	def like_post(self, post):
		if post.author != self.user:
			exec "Like.objects.get_or_create(%s=post, user=self.user)" % (post.classname().lower())

	def send_friend_request(self, receiver):
		FriendRequest.objects.get_or_create(sender=self.user, receiver=receiver)

hlndr_tumblr/users/forms.py
from django import forms

class RegisterForm(forms.Form):
	GENDER_CHOICES = ( ('u', 'Undisclosed'), ('m', 'Male'), ('f', 'Female') )


	username = forms.RegexField(regex=r'^[\w.@+-]+$',
								max_length=30,
								label="username",
								error_messages={
								'invalid':"This value may contain only letters, numbers and @/./+/-/_ characters."})
	password1 = forms.CharField()
	password2 = forms.CharField()
	email = forms.EmailField()
	birthday = forms.DateField()
	nickname = forms.CharField(required=False)
	gender = forms.ChoiceField(choices=GENDER_CHOICES)
	interests = forms.CharField(max_length=300, required=False)
	
class ImageForm(forms.Form):
	image = forms.FileField(required=True)

class ProfileForm(forms.Form):
	blogname = forms.CharField(max_length=100, required=False)
	nickname = forms.CharField(required=False)
	email = forms.EmailField(required=False)
	interests = forms.CharField(max_length=300, required=False)	
	
class PasswordForm(forms.Form):
	password1 = forms.CharField(required=True)
	password2 = forms.CharField(required=True)
		
class LoginForm(forms.Form):
	username = forms.RegexField(regex=r'^[\w.@+-]+$',
								max_length=30,
								label="username",
								error_messages={
									'invalid':"That username doesn't exist"})
	password = forms.CharField()

hlndr_tumblr/users/views.py
#Create your views here.
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.template import Context, loader, RequestContext
from django.utils import timezone
from django.shortcuts import get_object_or_404, render_to_response
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required

# from users.models import User
from users.forms import RegisterForm, LoginForm, ImageForm, ProfileForm, PasswordForm
from users.models import UserProfile

from utils.shortcuts import *

from blog.models import Blog
from following.models import Category
from favorites.models import FaveList

# display profile page
def profile(request, username):
    user = get_object_or_404(User,username=username)
    userprofile = get_object_or_404(UserProfile,user=user)
    return render_to_response('users/profile.html', {'user':user, 'userprofile':userprofile, 'request':request}, context_instance=RequestContext(request))

# display edit profile page and form
@login_required(login_url='/login/')
def edit_profile(request):
	if request.method == 'POST':
		# Get form type by submit request
		edit_action = request.POST['edit_action']
		if edit_action == "avatar":
			forms = ImageForm(request.POST, request.FILES)
		elif edit_action == "profile":
			forms = ProfileForm(request.POST)
		elif edit_action == "password":
			forms = PasswordForm(request.POST)
		else:
			return HttpResponseRedirect("/editprofile/")
		
		# Validate form
		if forms.is_valid():
			
			if edit_action == "avatar":
				file = request.FILES['image']
				#we may want to add an id field here to prevent user from accidently overriding
				filePath = "%s/ProfilePhoto/%s" % (request.user.username, file.name)
				s3_thread(file, filePath)
				request.user.userprofile.avatar = amazon_url + filePath
				request.user.userprofile.save()
				userName = request.user.username
				return HttpResponseRedirect("/%s/profile/" % userName)
			
			if edit_action == "profile":
				blogname = forms.cleaned_data['blogname']
				nickname = forms.cleaned_data['nickname']
				email = forms.cleaned_data['email']
				interests = forms.cleaned_data['interests']

				# save blog
				user_blog = Blog.objects.get(author=request.user)
				user_blog.title = blogname if blogname != user_blog.title else user_blog.title
				user_blog.save()
				
				# save user information
				user = request.user
				user.email = email if user.email != email else user.email
				user.save()

				# save profile information
				userprofile = request.user.userprofile
				userprofile.nickname = nickname if userprofile.nickname != nickname else userprofile.nickname
				userprofile.interests = interests if userprofile.interests != interests else userprofile.interests
				userprofile.save()
				
				return HttpResponseRedirect('/dashboard/')

			if edit_action == "password":
				return save_password_form(request, forms)
					
	imageform = ImageForm()
	profileform = ProfileForm()
	passwordform = PasswordForm()

	blog = Blog.objects.get(author=request.user)

	return render_to_response("users/editprofile.html",
							  {'user':request.user, 'blog':blog,
							  'imageform':imageform,'profileform':profileform,'passwordform':passwordform},
							  context_instance=RequestContext(request))

def save_password_form(request, form):
	password1 = form.cleaned_data['password1']
	password2 = form.cleaned_data['password2']

	if password1 != password2:	
		password_message = "Password mismatch"
	else:
		password_message = "Password Changed Successfully"
		request.user.set_password(password1)
		request.user.save()

	return render_to_response("users/editprofile.html",
							  {'user':request.user, 'imageform':ImageForm(), 
							   'profileform':ProfileForm(), 'passwordform':PasswordForm(), 'password_message':password_message},
							  context_instance=RequestContext(request))

# display list of friends page
@login_required(login_url='/friends/')
def friends(request):
	return render_to_response('users/friends.html',
							  {'users':request.user},
							  context_instance=RequestContext(request))

# login page
def log_in(request):
	if request.method == 'POST':
		form = LoginForm(request.POST)
		if form.is_valid():
			username = form.cleaned_data['username']
			password = form.cleaned_data['password']
			
			user = authenticate(username=username, password=password)
			if user is not None:
				if user.is_active:
					login(request, user)
					return HttpResponseRedirect('/dashboard/')
				else:
					return render_to_response('users/login.html',
											  {'form':form,
											   'invalid':"Account disabled"},
											  context_instace=RequestContext(request))
			else:
				return render_to_response('users/login.html',
										  {'form':form,
										   'invalid':"Invalid username or password"},
										  context_instance=RequestContext(request))

	template = loader.get_template('users/login.html')
	context = RequestContext(request)
	return HttpResponse(template.render(context))

@login_required(login_url='/login/')
def log_out(request):
	logout(request)
	return HttpResponseRedirect('/')

# registration page
def register(request):
	if request.method == 'POST':
		form = RegisterForm(request.POST)
		if form.is_valid():
			
			# Validate fields
			if form.cleaned_data['password1'] == form.cleaned_data['password2']:
				password = form.cleaned_data['password1']
			else:
				return render_to_response('users/register.html',
										  {'form':form,
										   'invalid':"Passwords mismatched"},
										   context_instance=RequestContext(request))
			
			# Django User Data
			username = form.cleaned_data['username']
			email = form.cleaned_data['email']
		
			# Validate unique user	
			if User.objects.filter(username=username).count() == 1:
				return render_to_response('users/register.html',
				     					  {'form':form,
						    			   'invalid':"User already exists"},
							    		   context_instance=RequestContext(request))
			# User Profile Data
			birthday = form.cleaned_data['birthday']
			nickname = form.cleaned_data['nickname']
			gender = form.cleaned_data['gender']
			interests = form.cleaned_data['interests']
			
			# Save User to database
			newuser = User(username=username,email=email)
			newuser.set_password(password)
			newuser.save()
			
			# save user profile to database
			user = User.objects.get(username=username)
			newUserProfile = UserProfile.objects.create(user=user,
														birthday=birthday,
														nickname=nickname,
														gender=gender,
														interests=interests)
			
			# Create user's blog information
			Blog.objects.create(author=user)
			# Create user's following information
			Category.objects.create(name="Uncategorized", owner=user.userprofile)
			# Create user's favelist
			FaveList.objects.create(user=user)
	
			return HttpResponseRedirect('/login/')
		else:
			return render_to_response('users/register.html',
									  {'form':form,
									   'invalid':"Some required fields have not been filled"},
									  context_instance=RequestContext(request))
	else:
		form = RegisterForm()

	return render_to_response('users/register.html',
							  context_instance=RequestContext(request))	

hlndr_tumblr/templates/users/editprofile.html
{% extends 'base.html' %}

{% block title %} {{ user.username }} &middot; Highlandr {% endblock %}

{% block content %}

<div class="container span8" id="center">
	<div class="row-fluid span12" style="min-height: 100%; margin:auto auto;">
		<div class="well container-fluid span8" id="center" style="background-color:#e7dd68;">

			<form action="/editprofile/" method="POST" enctype="multipart/form-data"> 
				{% csrf_token %}
				<h3> Profile Image (200 x 200): </h3>
				{{ imageform.image }}
				<button type="submit" name="edit_action" value="avatar" class="btn btn-inverse btn-block-level"> Upload </button>
			</form>

			<hr>

			<form action="/editprofile/" method="POST">
				{% csrf_token %}
				<strong>{{ blog_message }}</strong>
				<h4> Blog Title: </h4>
				<input type="text" name="blogname" class="input-block-level span5" placeholder="Blog Title" value="{{ blog.title }}">
				<h5> Nickname </h5>
				<input type="text" name="nickname" class="input-block-level span5" placeholder="Nickname" value="{{ user.userprofile.nickname }}">
				<h5> Email </h5>
				<input type="email" name="email" class="input-block-level span5" placeholder="Email" value="{{ user.email }}">
				<h5> Interests </h5>
				<textarea name="interests" class="span5" rows="5" placeholder="Interests, Comma, Separated">{{ user.userprofile.interests }}</textarea>
				<br><br>
				<button type="submit" name="edit_action" value="profile" class="btn btn-inverse btn-block-level"> Save </button>
			</form>

			<hr>

			<form action="/editprofile/" method="POST">
				{% csrf_token %}
				<strong>{{ password_message }}</strong>
				<h5> Change Password: </h5>
				<input type="password" name="password1" class="input-block-level span4" placeholder="Password">
				<input type="password" name="password2" class="input-block-level span4" placeholder="Password(again)">
				<br><br>
				<button type="submit" name="edit_action" value="password" class="btn btn-inverse btn-block-level"> Change Password </button>
			</form> 
			
			<hr>

			<a href="/{{ user.username }}/profile/" class="btn btn-block-level"> Cancel </a>

		</div>
	</div>
</div>

{% endblock %}

hlndr_tumblr/templates/users/login.html
{% extends 'base.html' %}

{% block title %} Login &middot; Highlandr {% endblock %}

{% block content %}

<div class="well container span3" style="margin-left: auto; margin-right: auto; float: none;">
	<form action="." method='POST' class="form-signin">
		{% csrf_token %}
		<h2> Log in </h2>
		<h5> {{ invalid }}</h5>
		<input type="text" value="{{ form.username.value }}" name="username" id="id_username" class="input-block-level" placeholder="Username">
		<input type="password" name="password" id="id_password" class="input-block-level" placeholder="Password">
		<button class="btn btn-large btn-primary" type="submit"> Log in </button>
		<a href="/register/" class="btn btn-large btn-primary"> Register </a>
	</form>
</div>
	
{% endblock %}

hlndr_tumblr/templates/users/profile.html
{% extends 'base.html' %}

{% block title %} {{ user.username }} &middot; Highlandr {% endblock %}

{% block content %}

<div class="container span4 offset3">
	<div class="row-fluid span12" style="min-height: 100%; margin:auto auto;">
		<div class="well container span12" id="profileblock">
			<h1> {{ user.username }} {% if user.userprofile.nickname != "" %} "{{ user.userprofile.nickname }}" {% endif %} </h1>
		</div>
		<div class="well container span12" id="profileblock">
			<h4> Gender: {{ user.userprofile.get_gender_display }} </h4>
			<h4> Email: <a type="email">{{ user.email }}</a> </h4>
			<h4> Birthday: {{ user.userprofile.birthday }} </h4>
			<h4> Date Joined: {{ user.date_joined }} </h4>
		</div>
		<div class="well container span12" id="profileblock">
			{% if user.userprofile.interests != "" %}
			<h4> Interests: <h4>
			<h4> {{ user.userprofile.interests|linebreaksbr }} </h4>
			{% endif %}
		</div>
	</div>
</div>

<div class="container span2">
	<div class="row-fluid span12" style="min-height: 100%; margin:auto auto;">
		<ul class="thumbnails">
			<div class="well container span12" id="profileblock" style="height: auto auto;">
				<a href="/{{ user.username }}/" class="thumbnail">
					{% if user.userprofile.avatar == "" %}
					<img src="../../static/img/default_avatar.png" height="200" width="200" class="img-rounded"></img>
					{% else %}
					<img src="{{ user.userprofile.avatar }}" height="200" width="200" class="img-rounded"></img>
					{% endif %}
				</a>
				<center>
				{% if user.username == request.user.username %}
				<a href="/editprofile/" class="btn btn-mini btn-info"><i class="icon-wrench icon-white"></i> Edit Profile </a>
				{% else %}
				{% endif %}
				</center>
			</div>
		</ul>
	</div>
</div>

{% endblock %}

hlndr_tumblr/templates/users/register.html
{% extends "base.html" %}

{% block title %} Register &middot; Highlandr {% endblock %}

{% block content %}
<div class="well container span4 offset4">
	<form action="/register/" method="POST">
		{% csrf_token %}
		<h2> Registration Form </h2>
		<h5> {{ invalid }} </h5>
		<input type="text" class="input-block-level" name="username" id="id_username" value="{{ form.username.value }}" placeholder="Username">
		<input type="text" class="input-block-level" name="nickname" id="id_nickname" value="{{ form.nickname.value }}" placeholder="Nickname (optional)">
		<input type="password" class="input-block-level" name="password1" value="{{ form.password1.value }}" id="id_password1" placeholder="Password">
		<input type="password" class="input-block-level" name="password2" value="{{ form.password2.value }}" id="id_password2" placeholder="Password (again)">
		<input type="email" class="input-block-level"  name="email" value="{{ form.email.value }}" id="id_email" placeholder="Email">
		<p> <strong> Birthday </strong> </p>
		<input type="date" class="input-block-level span5" name="birthday" value="{{ form.email.birthday }}" id="id_birthday">
		<p> <strong> Gender </strong> </p>


		
		<label class="radio inline">
			<input type="radio" name="gender" id="genderU" value="u"> Undisclosed
		</label>
		<label class="radio inline">
			<input type="radio" name="gender" id="genderM" value="m"> Male
		</label>
		<label class="radio inline">
			<input type="radio" name="gender" id="genderF" value="f"> Female
		</label>
		
		<textarea class="span12" style="margin: 20px 0px;" rows="5" name="interests" id="id_interests" placeholder="Interests, (optional), comma, separated"></textarea>
		<button type="submit" class="btn btn-large btn-primary"> Submit </button>
		<a href="/" class="btn btn-large"> Cancel </a>
	</form>
</div>
{% endblock %}